# Docker Compose file for CentralThing
# Test only!!! (Portainer)

version: '2.0'

services:
  reverse-proxy:
    image: traefik
    ports:
      - 80:80 
      - 8080:8080  # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    command: --api --docker


  portainer:
    ports:
      - 9000:9000
		volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
		command: -H unix:///var/run/docker.sock


  influxdb:
    image: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb


  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000/tcp
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.port=3000"

 
  nodered:
    image: nodered/node-red-docker
    ports:
      - 1880:1880
      - 9229:9229
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/nodered:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nodered"
      - "traefik.port=1880"