# Docker Compose file for CentralThing
# Test only!!!

version: '2.0'

services:
  reverse-proxy:
    image: traefik  # The official Traefik docker image
    command: --api --docker  # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"      # The HTTP port
      - "8080:8080"  # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events


  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb


  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3001:3000/tcp
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.port=3000"

 
  nodered:
    image: nodered/node-red-docker:v8
    ports:
      - 1880:1880
      - 9229:9229
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/nodered:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nodered"
      - "traefik.port=1880"